In [7]:
# import load_iris function from datasets module
from sklearn.datasets import load_iris

# save "bunch" object containing iris dataset and its attributes
iris = load_iris()

# store feature matrix in "X"
X = iris.data

# store response vector in "y"
y = iris.target

In [8]:
# print the shapes of X and y
print X.shape
print y.shape

(150L, 4L)
(150L,)


In [9]:
# scikit-learn 4-step modeling pattern
# Import the class you plan to use
from sklearn.neighbors import KNeighborsClassifier

In [13]:
# Instantiate the estimator
knn = KNeighborsClassifier(n_neighbors=1)

In [14]:
print knn
# scikit has sensible defaults

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [15]:
# 3. Fit the model with data
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [16]:
# 4. Make predictions for a new observation
knn.predict([3, 5, 4, 2])

C:\Users\William\Anaconda2\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [18]:
# KNN predicted that it was the Virginia type of flower (2).
# We will try with two inputs now

X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(X_new)

array([2, 1])

In [19]:
# Let's use a different value for k
knn = KNeighborsClassifier(n_neighbors=5)

# fit the model with data
knn.fit(X,y)

# predict the response for new observations
knn.predict(X_new)

array([1, 1])

In [20]:
# Using a different classification model
# import the model
from sklearn.linear_model import LogisticRegression

# instantiate the model (using the default parameters)
logreg = LogisticRegression()

# fit the model with data
logreg.fit(X, y)

# predict the response for new observations
logreg.predict(X_new)

array([2, 0])

In [ ]:
# Which model was better?
# We don't know... We were using made-up numbers so we don't know which
# one was more accurate